# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPollution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pollutants', models.CharField(max_length=200)),
            ],
        ),
    ]
