# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-07 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_application', '0004_watern_waternh3_waterno3_watero2_waterp_waterpo4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterPollution',
            new_name='greenhouse',
        ),
    ]
