# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_application', '0005_auto_20191207_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='deforestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('recent_year', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
